//
//  ArchiveView.swift
//  Olympsis
//
//  Created by Joel Joseph on 6/12/26.
//

import SwiftUI

/// The window of past events the archive should display.
///
/// The raw value is the number of months back from today, which is also used to
/// persist the user's selection via `@AppStorage`.
enum ArchiveRange: Int, CaseIterable, Identifiable {
    case oneMonth = 1
    case threeMonths = 3
    case sixMonths = 6

    var id: Int { rawValue }

    /// Number of months to subtract from today to find the start of the range.
    var months: Int { rawValue }

    var label: String {
        switch self {
        case .oneMonth:
            return String(localized: "archive-range-1-month", defaultValue: "Last Month", table: "Profile")
        case .threeMonths:
            return String(localized: "archive-range-3-months", defaultValue: "Last 3 Months", table: "Profile")
        case .sixMonths:
            return String(localized: "archive-range-6-months", defaultValue: "Last 6 Months", table: "Profile")
        }
    }
}

/// Groups the events that belong to a single calendar month for display.
private struct MonthGroup: Identifiable {
    let date: Date          // First day of the month, used for sorting/formatting.
    let events: [Event]
    var id: Date { date }
}

/// Inline archive of the user's past events shown on the profile page.
///
/// On first appearance the archive is generated by fetching the user's past events and is then
/// cached to disk. Subsequent visits load straight from the cache (no network). The full fetched
/// set is cached, so switching between the 1/3/6 month ranges just re-filters in memory and never
/// triggers another fetch — the user can force a refresh from the range menu.
struct ArchiveView: View {

    /// Persisted range selection (defaults to the last 3 months).
    @AppStorage("archive_range") private var range: ArchiveRange = .threeMonths

    /// The full set of fetched past events backing the archive (cached to disk).
    @State private var allEvents: [Event] = []
    @State private var isLoading = false

    @Environment(SessionStore.self) private var session

    // MARK: - Derived data

    /// The start of the currently selected range.
    private var rangeStart: Date {
        Calendar.current.date(byAdding: .month, value: -range.months, to: Date()) ?? Date()
    }

    /// Events that fall within the selected range, most recent first.
    private var events: [Event] {
        allEvents
            .filter { $0.startTime >= rangeStart }
            .sorted { $0.startTime > $1.startTime }
    }

    /// Events grouped by calendar month, most recent month first.
    private var monthlyGroups: [MonthGroup] {
        let calendar = Calendar.current
        let grouped = Dictionary(grouping: events) { event in
            calendar.dateComponents([.year, .month], from: event.startTime)
        }
        return grouped
            .map { components, events in
                MonthGroup(date: calendar.date(from: components) ?? Date(),
                           events: events.sorted { $0.startTime > $1.startTime })
            }
            .sorted { $0.date > $1.date }
    }

    // MARK: - Stats

    private var totalPlayed: Int { events.count }

    private var totalSports: Int {
        Set(events.flatMap { $0.sports.map { $0.lowercased() } }).count
    }

    private var totalVenues: Int {
        // Identify a venue by its id when available, otherwise fall back to its name so that
        // external (non-vetted) venues are still counted distinctly.
        Set(events.flatMap { $0.venues.compactMap { $0.id ?? $0.name } }).count
    }

    private var totalHours: Int {
        let seconds = events.reduce(0.0) { $0 + $1.stopTime.timeIntervalSince($1.startTime) }
        return Int((seconds / 3600).rounded())
    }

    /// Human readable span of the selected range, e.g. "Mar – Jun 2026".
    private var rangeHeader: String {
        let now = Date()
        let calendar = Calendar.current

        let monthFormatter = DateFormatter()
        monthFormatter.locale = Locale(identifier: Locale.current.identifier)
        monthFormatter.dateFormat = "MMM"

        let yearFormatter = DateFormatter()
        yearFormatter.locale = Locale(identifier: Locale.current.identifier)
        yearFormatter.dateFormat = "yyyy"

        let startMonth = monthFormatter.string(from: rangeStart)
        let endMonth = monthFormatter.string(from: now)
        let endYear = yearFormatter.string(from: now)

        // Only print the start year when it differs from the end year.
        if calendar.component(.year, from: rangeStart) == calendar.component(.year, from: now) {
            return "\(startMonth) – \(endMonth) \(endYear)"
        } else {
            let startYear = yearFormatter.string(from: rangeStart)
            return "\(startMonth) \(startYear) – \(endMonth) \(endYear)"
        }
    }

    // MARK: - Body

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            header

            if isLoading {
                HStack {
                    Spacer()
                    ProgressView()
                        .padding(.vertical, 40)
                    Spacer()
                }
            } else if events.isEmpty {
                emptyState
            } else {
                statsRow
                ForEach(monthlyGroups) { group in
                    monthSection(for: group)
                }
            }
        }
        .padding(.horizontal)
        .task {
            await loadArchive()
        }
    }

    // MARK: - Subviews

    @ViewBuilder
    private var header: some View {
        HStack(alignment: .firstTextBaseline) {
            Text(String(localized: "archive-title", defaultValue: "Archive", table: "Profile"))
                .font(.title)
                .fontWeight(.bold)

            Spacer()

            // The range menu doubles as the date-range label: tapping it lets the user switch
            // the window or force a fresh generation.
            Menu {
                Picker(selection: $range) {
                    ForEach(ArchiveRange.allCases) { option in
                        Text(option.label).tag(option)
                    }
                } label: {
                    EmptyView()
                }

                Divider()

                Button {
                    Task { await generateArchive() }
                } label: {
                    Label(String(localized: "archive-refresh", defaultValue: "Refresh", table: "Profile"),
                          systemImage: "arrow.clockwise")
                }
            } label: {
                HStack(spacing: 4) {
                    Text(rangeHeader)
                    Image(systemName: "chevron.down")
                        .font(.caption2)
                }
                .font(.subheadline)
                .foregroundStyle(.gray)
            }
        }
    }

    @ViewBuilder
    private var statsRow: some View {
        HStack(spacing: 0) {
            statCell(value: totalPlayed,
                     label: String(localized: "archive-stat-played", defaultValue: "PLAYED", table: "Profile"))
            divider
            statCell(value: totalSports,
                     label: String(localized: "archive-stat-sports", defaultValue: "SPORTS", table: "Profile"))
            divider
            statCell(value: totalVenues,
                     label: String(localized: "archive-stat-venues", defaultValue: "VENUES", table: "Profile"))
            divider
            statCell(value: totalHours,
                     label: String(localized: "archive-stat-hours", defaultValue: "HOURS", table: "Profile"))
        }
        .padding(.vertical, 8)
    }

    @ViewBuilder
    private func statCell(value: Int, label: String) -> some View {
        VStack(spacing: 4) {
            Text("\(value)")
                .font(.title2)
                .fontWeight(.bold)
                .foregroundStyle(.primary)
            Text(label)
                .font(.caption2)
                .fontWeight(.medium)
                .foregroundStyle(.gray)
        }
        .frame(maxWidth: .infinity)
    }

    @ViewBuilder
    private var divider: some View {
        Rectangle()
            .frame(width: 1, height: 30)
            .foregroundStyle(Color.border)
    }

    @ViewBuilder
    private func monthSection(for group: MonthGroup) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack(alignment: .firstTextBaseline, spacing: 8) {
                Text(monthTitle(for: group.date))
                    .font(.headline)
                    .fontWeight(.bold)

                Text(monthSubtitle(for: group))
                    .font(.caption)
                    .foregroundStyle(.gray)

                Spacer()
            }
            .padding(.top, 8)

            ForEach(group.events, id: \.id) { event in
                NavigationLink {
                    EventView(event: event)
                        .environment(event)
                        .environment(session)
                } label: {
                    EventSmallListItem(event: event)
                }
                .buttonStyle(.plain)
            }
        }
    }

    @ViewBuilder
    private var emptyState: some View {
        HStack {
            Spacer()
            VStack(spacing: 4) {
                Text(String(localized: "archive-empty-title", defaultValue: "No events in this period", table: "Profile"))
                Text(String(localized: "archive-empty-subtitle", defaultValue: "Go find some", table: "Profile"))
                    .font(.caption)
                    .fontWeight(.bold)
                    .foregroundStyle(.gray)
            }
            .padding(.vertical, 40)
            Spacer()
        }
    }

    // MARK: - Formatting helpers

    /// e.g. "June 2026"
    private func monthTitle(for date: Date) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: Locale.current.identifier)
        formatter.dateFormat = "MMMM yyyy"
        return formatter.string(from: date)
    }

    /// e.g. "6 events · Soccer, Tennis"
    private func monthSubtitle(for group: MonthGroup) -> String {
        let countText = group.events.count == 1
            ? String(localized: "archive-event-count-single", defaultValue: "1 event", table: "Profile")
            : String(localized: "archive-event-count", defaultValue: "\(group.events.count) events", table: "Profile")

        let sports = Set(group.events.flatMap { $0.sports })
            .map { $0.capitalized }
            .sorted()
            .joined(separator: ", ")

        return sports.isEmpty ? countText : "\(countText) · \(sports)"
    }

    // MARK: - Data loading

    /// Loads the archive, preferring the on-disk cache and only generating (fetching) when
    /// nothing has been cached yet.
    private func loadArchive() async {
        guard allEvents.isEmpty else { return }

        if let cached = session.cacheService.fetchArchivedEvents() {
            allEvents = cached
        } else {
            await generateArchive()
        }
    }

    /// Generates the archive by fetching the user's past events and caching the result.
    private func generateArchive() async {
        isLoading = true
        defer { isLoading = false }

        let pastEvents = await session.eventService.fetchPastEvents()
        allEvents = pastEvents
        session.cacheService.cacheArchivedEvents(pastEvents)
    }
}

#Preview {
    ScrollView {
        ArchiveView()
            .environment(SessionStore())
    }
}
